# Generated code from Antlr4BuildTasks.dotnet-antlr v <version>
name: cli
description: A sample command-line application.
environment:
  sdk: '>=2.8.1 \<3.0.0'
dependencies:
  antlr4: 4.9.2
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4


