# Template generated code from trgen <version>
name: cli
description: A sample command-line application.
environment:
  sdk: '>=2.12.0 \<3.0.0'
dependencies:
  antlr4: 4.9.3
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4


